# Generated by Django 2.2.2 on 2019-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user_id_1',
        ),
    ]
